### PR TITLE
Enable usage of different uuid versions

### PR DESCRIPTION
**Pull request by christian-kolb**
## Changes

- Dropped `final` keyword for `Id->generateRandom()` to enable custom construction of UUID V7 ids.
- Added documentation for `generateRandom` override.
- Adapted docs in preparation for the next release.

## Dev setup changes

- Added caching in CI actions.
- Added custom docker images to prevent build failures in the CI.

### CODE REVIEW

**Comment by christian-kolb** [comment]
@scuben Changes are released in `0.12.0` 🙂 Thanks for the input.

**Comment by plandolt** [comment]
Will start using it tomorrow! Thank you and sorry for all the work to remove a handful of characters 🤣

**Comment by christian-kolb** [comment]
No worries, better to have a lot of work with a few characters then putting in hundreds of lines of code that have to be managed indefinitely 😄

**Comment by christian-kolb** [comment]
@plandolt I stumbled over the this [article](https://hackernoon.com/the-quiet-bottleneck-in-your-symfony-app-fragmented-indexes-and-random-uuids) that describes the performance impact of uuid 4 vs uuid 7. I'm not sure whether that actually has an impact on the applications I'm working on, but I'm evaluating whether it makes sense to add some kind of parameter to `generateRandom` or a configuration to the Id subclasses to configure which uuid version should be generated. Uuid 7 is not supported by the uuid extension. Did you by any chance already look into the performance implications of which uuid library takes how long to generate uuid v7?

**Comment by plandolt** [comment]
@christian-kolb So far I just used the symfony/uuid component to generate v7 uuid. But if you have version 1.3 of the uuid extension you should be able to generate v7 uuids with the extension: https://pecl.php.net/package-changelog.php?package=uuid&release=1.3.0.

**Comment by christian-kolb** [comment]
@plandolt Perfect, I looked into locally but didn't realize that I still have the old 1.1 version. Thanks for the important note. I'll look into how useful it would be in reality 🙂

**Pull request merged**
