### PR TITLE
symfony uid

### PR DESCRIPTION
**Pull request by plandolt**
This is a concept to allow `Uid` instances from the symfony uid component. The goal was to use `uuid version 7`. This solves the problem that the regular `Id` class only generates `uuid v1` when using `generateRandom`.

@christian-kolb wdyt?

### CODE REVIEW

**Comment by christian-kolb** [comment]
Thanks for the PR. I've got a few questions and it's possible that the goal of this package isn't communicated well enough and this PR might clash with the original intend. But let's see, maybe we can square those things 🙂

Idea behind the package: I want to use UUIDs, but in a typed variant, so that it's not possible to supply an id of a user to a function that expects the id of a project. On the other side this should be as performant and as lightweight as possible. Before this package, I've used ramsey/uuid which can do basically everything. But we got performance problems with it, as we have requests where thousands of ids are handled at once. And millions in a job queue run. That's why the whole package is basically just an object and minimal utility wrapper around the uuid extension. The suggested polyfill is just a workaround, but not meant to be used as it's already way less performant.

Symfony Uuid is a thin variant of ramsey/uuid, but already contains more then just the uuid string in it's objects. So unfortunately it goes against the performance aspect of this package. And I might question why someone would use this package when using Symfony Uuid, because you can do everything with it that you can with this package (maybe apart from the id list).

Now to the UUID version topic: The UUIDs created by `uuid_create` are actually v4. I've just checked to make sure and they all look like this `e264864d-8cd8-4e29-b100-aacbfaa09e10` meaning with 4 at `{}` `e264864d-8cd8-{4}e29-b100-aacbfaa09e10`.

The package doesn't really care about which version is used. If the `uuid_is_valid` says it's valid, it's good enough. Do you know if it's possible to generate V7 through the uuid extension and the uuid polyfill? Because then we could add some kind of "configuration" in the object for that and would still be in line with all the goals of the package 🙂

**Comment by plandolt** [comment]
Thank you very much for your detailed answer. I fully understand the goal of the package, and can definitely understand if you want to keep the scope of the package as narrow as possible. My goal with the PR is that you can still use an object as an id in the entity, but the uuid can be used in v7.

The PECL package can successfully validate `uuid_is_valid` uuid v7, but cannot create one with `uuid_create`.

The PR is aimed at having different `Id` classes. The existing one and a new one that can be used with the Symfony uid component. In the same style, it would also be possible to implement further `Id` classes, e.g. for `ramsey/uuid` (via PR or independently in a project).

However, a much simpler option would be to no longer declare the `generateRandom` method as final, so that it can be overwritten by a project-specific `Id` class, which `Id` extends, in order to leave the generation of a random uuid to the project. An even better approach would be to extract the create process (which is uuid_create) to a separate method and only allow this method to be overwritten by a project specific `Id` class. I have created a [PR](https://github.com/digital-craftsman-de/ids/pull/58) for this, which in retrospect is probably the better solution for my goal.

**Comment by christian-kolb** [comment]
Ok, so if it's at least possible to use validate on it, then there is nothing in the way of enabling V7 generation.

I'd like to prevent abstraction as much as possible. So introducing another function that is called every time, feels bad to me personally. Wouldn't having an additional function call also have performance implications?
What does make it "an even better approach" in your opinion? 🙂

I like the idea of having a non final `generateRandom`.

**Comment by plandolt** [comment]
I initially tought that the intend would be clearer. But in the end in practical use `create` would just be the same as `generateRandom`. Thus I updated the PR.

**Comment by christian-kolb** [comment]
Great 🙂
I'll add a little bit of documentation to your PR later and we can get it merged then!

**Comment by christian-kolb** [comment]
Handled in PR #59

**Pull request closed without merging**
